### ISSUE TITLE
cli: support for github actions YAML syntax

### ISSUE THREAD

**Issue by mznet** [getpopper/popper#748]
I'm looking for the tool running github action locally. popper and [act](https://github.com/nektos/act) might be a my choice but neither doesn't support `yaml` yet. Workflows I wrote are based on yaml not hcl. Is there any plans to support `yaml`?

**Comment by JayjeetAtGithub** [comment]
Hi @mznet, Thanks for opening this issue. Yes, we do have future plans to add support for `yaml` syntax.

**Comment by ivotron** [comment]
@mznet thanks for creating this! I'll reopen it and use this to track progress of work for this feature

**Comment by mznet** [comment]
@ivotron Was the Future plan changed?

**Comment by vipulchhabra99** [comment]
Hi @ivotron @JayjeetAtGithub, I would like to work on this issue, I have presented my sample idea on the Gitter channel. If my idea sounds good to you, I can start working on it.

**Comment by ivotron** [comment]
thanks @vipulchhabra99! For posterity, can you please post your idea here?

**Comment by vipulchhabra99** [comment]
Yeah sure @ivotron, My idea is to support both HCL and YAML syntax. What I plan to do is to create a layer that will check the type of syntax used in workflow based on that It will parse using the appropriate library and convert it to the standard format of python dictionary while the other validation rules will remain unaffected and rest of the flow would remain same.

**Comment by ivotron** [comment]
thanks @vipulchhabra99, that's a great start. Since this is a complex feature, we would benefit from first writing a high-level document such as [an RFC](https://github.com/cockroachdb/cockroach/tree/master/docs/RFCS) (see a template [here](https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/00000000_template.md)). We can put this in a new `docs/rfcs/` folder. This would allow us to discuss ideas and other high-level things before writing code, which in turn would avoid the scenario where code gets written unnecessarily. You can open a PR first only for the RFC, and we use that PR to discuss the ideas. Would that work?

Some comments follow:
  * We have a parser class that @JayjeetAtGithub implemented in the `cli/popper/parser.py` module. We can refactor and create HCLParser and YAMLParser classes; then we can instantiate parsers based on the extension of a file (`.yml` vs `.workflow`).
  * I am not sure if the `Workflow` class can capture the logic in a YAML syntax (this would be part of the work needed to be done for writing the RFC).
  * Assuming we had a `Workflow` representation for yaml syntax, the `WorkflowRunner` cannot run a this workflow "as is" because there are features in the YAML-syntax that the HCL flavor does not support (e.g. conditionals, javascript actions, among many many others). In other words, the YAML logic is a superset (or maybe even an intersection?) of the one expressed in HCL. So the `WorkflowRunner` class will definitely need to be extended in order for it to fully support YAML.
  * For ideas on how to implement this, you can check the analogous issue for the `act` project (https://github.com/nektos/act/issues/74)

**Comment by vipulchhabra99** [comment]
Thanks @ivotron, Actually I haven't much worked before with YAML and thought it to be similar like HCL but since you mentioned some of the features like conditional, js actions, etc. Then I believe that the parsing would be done differently so for this I think I need to learn more about YAML and the already available parsing libraries and how I can convert parsed workflow to standard python dictionary which is generated by HCL syntax. For It, I will require some time to get the basic knowledge that will be required to proceed further. Once I am done with it I will ping here and start soon.

**Comment by ivotron** [comment]
sounds good. FWIW, parsing YAML and generating a `Workflow` object is relatively easier compared to the more difficult problem of having the `WorkflowRunner` execute a YAML-syntax workflow, due to the complexity of the underlying logic

**Comment by vipulchhabra99** [comment]
I was going through the above thread that you mentioned there they mentioned two tools migrate and yj. Migrate has been taken down by the GitHub but yj is still available but the problem they mentioned it that on converting HCL to YAML using yj generate a file that may not be accepted by GitHub so, for the time being, can we use it to convert a YAML file to HCl and then use it?

**Comment by ivotron** [comment]
that's unfortunately not going to work. The language is different, so the HCL-translated version of a YAML workflow will look significantly different from a `.workflow` file.

**Comment by vipulchhabra99** [comment]
ok @ivotron, Then the solution as you mentioned in comments would be the best one I am currently working on the basics and will start working soon.

**Comment by vipulchhabra99** [comment]
Hi @ivotron, Can you provide me some sample workflows which will require special parsing rather than only loading via the yaml-parsing library.

**Comment by ivotron** [comment]
@vipulchhabra99 I'm not sure I understand your question, all workflows in YAML syntax can be parsed with a YAML parsing library. Can you please provide more info so I can understand better?

**Comment by vipulchhabra99** [comment]
Like you mentioned that workflows containing conditionals, js actions, etc need to have special parsing after loading through the YAML library. I want to try it out and understand it.

**Comment by ivotron** [comment]
I see. You can take a look at examples here: https://github.com/actions/starter-workflows

**Comment by edeediong** [comment]
@JayjeetAtGithub @ivotron Is this still an issue? The commit history shows @JayjeetAtGithub has already fixed this.

**Comment by JayjeetAtGithub** [comment]
Thanks for noticing @edeediong. Work on the support of YAML syntax is still left in the sense that all the tests need to be ported to `yaml` syntax also. This is being tracked by #780. So, maybe we can keep this open until #780 gets done.

**Comment by ivotron** [comment]
sorry for the confusion. This issue deals with adding support for running workflows specified in [Github Actions YAML syntax](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions). What got merged in #779 is another form of YAML syntax that is inspired by [Google Cloud Build's](https://cloud.google.com/cloud-build/docs/build-config), which is different. I've renamed the issue to make it clearer.
