### ISSUE TITLE
cli: singularity build should not print logs to terminal

### ISSUE THREAD

**Issue by JayjeetAtGithub** [getpopper/popper#815]

**Comment by ivotron** [comment]
Does this happen even with `--quiet` is given? The behavior should be to show the output of build unless `--quiet` is given. There's an open issue to fix this for Docker #785

**Comment by JayjeetAtGithub** [comment]
Yes. I have added `self._s.quiet = True` in singularity runner. I have to check once again.

> The behavior should be to show the output of build unless --quiet is given. There's an open issue to fix this for Docker #785

Yeah, this same issue reflects is singularity runner also.

**Comment by ivotron** [comment]
> Yes. I have added `self._s.quiet = True` in singularity runner. I have to check once again.

sorry, I think I didn't explain myself well. I was referring to `popper run` in general, not to a runner specifically. What I meant was that if we do:

```bash
popper run -f wf.yml
```

the output should include build-related logs. Whereas if we pass the `--quite` flag, it shouldn't.

> 
> > The behavior should be to show the output of build unless --quiet is given. There's an open issue to fix this for Docker #785
> 
> Yeah, this same issue reflects is singularity runner also.

In the case of Docker, the issue is the opposite though. Currently with the docker runner, the output of building an image is NOT shown, but it should. Whereas for singularity, based on you describe, what we have is that the output of build does get shown.

**Comment by JayjeetAtGithub** [comment]
Yeah. Now, the `--quiet` flag doesn't affect the build / pull logs, so it is what we have to check and fix.
