### ISSUE TITLE
cli: Custom Dockerfile fails with upper-case step ID

### ISSUE THREAD

**Issue by wtraylor** [getpopper/popper#849]
# Steps to reproduce
```bash
git init myrepo
cd myrepo
# Create "wf.yml" with the content below
mkdir popper
echo "FROM alpine:latest" > mydocker/Dockerfile
popper run -f wf.yml
```
`wf.yml` looks like this:
```yaml
steps:
- id: Do Something # At least one capital letter.
  uses: ./mydocker
  args: [echo, "hello world"]
```
## Error message
```
[Do Something] docker build popper_Do_Something_step:0e17abb /home/user/myrepo/./mydocker
ERROR: 500 Server Error: Internal Server Error ("invalid reference format: repository name must be lowercase")
```
If the step ID is all lower-case (`id: do something`), there is no error.
## Versions
- Popper version: Current `master`, in virtual environment with Python 3.8.3
- Operating system: Arch Linux
- Docker version 19.03.11-ce, build 42e35e61f3

# Expected behavior
- Popper warns the user if an ID in the workflow file is not all lowercase, or
- Popper converts the ID to lowercase when calling Docker.

**Comment by ivotron** [comment]
thanks for the detailed report @wtraylor!

So we're not sanitizing step `id`s and that's causing this error. This would be fixed by modifying the workflow YAML spec, specifically [the entry for `id`s](https://github.com/getpopper/popper/blob/09f0cbd/cli/popper/parser.py#L27). We can change that from type `str` to [type `regex`](https://pykwalify.readthedocs.io/en/unstable/validation-rules.html#pattern) and specify something like:

```yaml
"id": {"type": "regex", "pattern": "^[a-z0-9]+"}
```

And also it would be useful to add tests so this is now checked.

P.S. PR more than welcome 😄

**Comment by fsr313** [comment]
I'd like to help with this, but have a question about this. 
When handling the exception of the validation, log.fail sends sys.exit(1), how should I make a test for this?

**Comment by ivotron** [comment]
thanks @fsr313, do you mean that you would like to write a test such that you ensure that given a certain input, the application fails? If that's the case, then you can look at an example of how this is done [here](https://github.com/getpopper/popper/blob/60c7701/src/test/test_parser.py#L27). If not, can you please expand a bit on what you mean by "when handling the exception of the validation"? thanks!

**Comment by ivotron** [comment]
sorry @fsr313 , I made a mistake and described the fix improperly. It should be possible to have step ids like the following:

```yaml
steps:
- id: This is Valid
  uses: docker://alpine:3.12
  args: [ls]
```

So instead of modifying the spec, what we need to do is to actually [modify this line](https://github.com/getpopper/popper/blob/60c7701/src/popper/runner_host.py#L246), which is where the name of a container is obtained, so that the name is transformed (no lower case, no spaces, only underscores).

apologies again for providing incorrect directions

**Comment by fsr313** [comment]
I don't think that will help with the Issue, instead converting to lower-case the step when getting the build info will solve the issue [this line](https://github.com/getpopper/popper/blob/60c7701cfe345d6183d6adce4232964be73fee2f/src/popper/runner_host.py#L196)

**Comment by ivotron** [comment]
> I don't think that will help with the Issue. instead converting to lower-case the step when getting the build info will solve the issue [this line](https://github.com/getpopper/popper/blob/60c7701cfe345d6183d6adce4232964be73fee2f/src/popper/runner_host.py#L196)

yes, that's indeed where it has to be modified, thanks a lot for checking!

**Comment by fsr313** [comment]
I updated my pull request, making the needed changes to fix this issue, spaces are handled by the sanitized_name function from utils. Also modifies a test to check for id using upper-case

**Comment by fsr313** [comment]
@ivotron ?
