### ISSUE TITLE
Issue with `uses` and `args` attributes' paths in wf.yml file

### ISSUE THREAD

**Issue by phesse001** [getpopper/popper#886]
So before I was able to successfully run a popper workflow with the following `wf.yml` file:

 (0) Start of file
steps:

 (1) Run March Madness Application
- uses: './container'
  runs: ['./scripts/madness.sh']

 (3) Create LaTeX Table with results
- uses: docker://python:3
  runs: ['./scripts/table.py','./scripts/correct.txt','./madness/output_no_advantage.txt', './madness/output_2_advantage.txt','./madness/output_4_advantage.txt','./docker_table.tex','12']

 (4) Compile Latex files into pdf
- uses: './container'
  runs: ['./paper.sh']

 (5) Remove March Madness Application from host machine
- uses: './container'
  args: ['rm', '-r', 'madness']

Now, when I try to run this file I immediately get the following error `[1] docker build popper_1_step:{} /home/patrick/Trust-Tools/popper_solution/./container
ERROR: 500 Server Error: Internal Server Error ("invalid reference format")
`
container is a directory in the same directory as the `wf.yml` file which contains a Dockerfile which is used in 3 of the 4 steps.

Whatever I change the `uses` attribute I either get a `invalid url` error or some other weird error.

The documentation notes: "A step in a workflow can reference a container image defined in a Dockerfile that is part of the same repository where the workflow file resides" but even when I move the Dockerfile outside of the container directory to the same directory as the one with the `wf.yml` file, I don't know how to refer to it as any path(just stating 'Dockerfile', or '/full/path/to/Dockerfile') all give me invalid url errors and when I give the uses attribute './Dockerfile' gives me `ERROR: You must specify a directory to build in path` which seems like a Docker error?

Has anything changed with the versioning of Docker and Popper that makes certain versions cause this error, or is this a syntax error in the wf.yml file?

The full repo can be cloned [here](https://github.com/betterscientificsoftware/Trust-Tools) if anyone wants to try to reproduce the error. Any help/suggestions are very much appreciated!

**Comment by ivotron** [comment]
thanks a lot for reporting this @phesse001 . I'm able to reproduce. I'll push a fix shortly

**Comment by ivotron** [comment]
I spoke too soon. I can reproduce the behavior you described, but I did it by creating a small project that is _not_ inside a Git repository:

```
myproj/
   container/Dockerfile
   wf.yml
```

the content of `wf.yml` is:

```yaml
steps:
- uses: ./container
  args: [ls, -l]
```

the `Dockerfile`:

```
FROM alpine:3.12
```

and then running:

```
cd myproj
popper run -f wf.yml
```

The above is a regression introduced in 2.6.0. And the above works fine on 2.5.0. I'm working on a fix and will publish 2.7.1 with this fix.

-------------

For the repo you shared though, I couldn't reproduce the error. This works OK:

```
git clone https://github.com/betterscientificsoftware/Trust-Tools/
cd popper_solution
chmod +x scripts/madness.sh
popper run -f wf.yml
```

Note how I had to make the script executable so it would run fine in the container, otherwise an error is thrown:

```
ERROR: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:349:
 starting container process caused "exec: \"./scripts/madness.sh\": permission denied": u
nknown")
```

**Comment by phesse001** [comment]
Ok. Cloning a fresh version myself and then running the same commands that worked for you for some reason does not work for me.

After cloning the repo these are the commands I ran in my terminal:

(base) patrick@patrick-Virtual-Machine:~/popper-test$ cd popper_solution
(base) patrick@patrick-Virtual-Machine:~/popper-test/popper_solution$ chmod +x scripts/madness.sh
(base) patrick@patrick-Virtual-Machine:~/popper-test/popper_solution$ sudo popper run -f wf.yml
[1] docker build popper_1_step:{} /home/patrick/popper-test/popper_solution/./container
ERROR: 500 Server Error: Internal Server Error ("invalid reference format")

My version of Docker is 19.03.11 and Popper is 2.7.0

Is there any conflicts with these versions you know of, or any idea as to what could be causing my issues?

**Comment by ivotron** [comment]
can you please show the output of `popper version` and `which python`? did you install popper using pip or the installer script shown in the README?

**Comment by ivotron** [comment]
sorry, I meant `which popper`

**Comment by phesse001** [comment]
Here is the output of `popper --version` and `python --version` from my terminal

(base) patrick@patrick-Virtual-Machine:~$ sudo popper --version
[sudo] password for patrick: 
Popper version 2.7.0

I installed it using the installer script. Does popper have any sort of `popper uninstall` command or would I have to manually remove it?

Side note: I was recently trying to integrate the travisCI into the project, which the original command didn't work because it wasn't installing popper properly so I instead just took the install.sh file and modified it to not take interactive input. However I wouldn't expect this to have any effect as that would only install it in the travis image. Once that worked is when I noticed the popper error, and tried it locally and got the same error I saw in travis.

**Comment by ivotron** [comment]
> I installed it using the installer script. Does popper have any sort of `popper uninstall` command or would I have to manually remove it?

the installer creates a single script in the directory where it was executed from, or to `/usr/local/bin/popper` if you select it to be moved to that location. So removal is manually done by deleting this script.
 
> Side note: I was recently trying to integrate the travisCI into the project, which the original command `popper ci --file wf.yml travis` didn't work because it wasn't installing popper properly so I instead just took the install.sh file and modified it to not take interactive input. However I wouldn't expect this to have any effect as that would only install it in the travis image. Once that worked is when I noticed the popper error, and tried it locally and got the same error I saw in travis.

yeah, that should be fine.

--------

I can't reproduce the issue locally. I _think_ it might be due to the use of `sudo` on your end. Can you try without `sudo`?

I also couldn't reproduce on travis for the repo you shared (I opened https://github.com/betterscientificsoftware/Trust-Tools/pull/2)

**Comment by phesse001** [comment]
when I run without sudo I get 
`popper run -f wf.yml
WARNING: Error loading config file: /home/patrick/.docker/config.json: stat /home/patrick/.docker/config.json: permission denied
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.

I also get a permission denied error when it runs ./scripts/table.py for the travis build, not sure if that is caused by the same thing but I'll try to figure out this daemon socket issue and get back if it fixes everything on my end.

**Comment by phesse001** [comment]
after fixing the docker permission errors and running without sudo the problem still persists

`(base) patrick@patrick-Virtual-Machine:~/Trust-Tools/popper_solution$ popper run -f wf.yml
[1] docker build popper_1_step:{} /home/patrick/Trust-Tools/popper_solution/./container
ERROR: 500 Server Error: Internal Server Error ("invalid reference format")
`

**Comment by ivotron** [comment]
hey @phesse001, could you please give it a try with the latest `master`? I pushed a fix for this issue that should resolve the problem.

**Comment by phesse001** [comment]
I tried installing with both the curl link and cloning and both give me the exact same error as before. Later tonight I will try getting a fresh image of ubuntu, downloading docker and popper, and then clone the repository and test it on the fresh ubuntu image.

**Comment by ivotron** [comment]
the installer script points to the latest tagged release, so that won't contain this change. But you can tweak the script so that it uses `getpopper/popper:latest` instead of `getpopper/popper:v2.7.0`. Or alternatively you install with pip. If there seems to be now change when you change versions, it might be that when you run `popper` it is picking an old binary instead of the one you just installed. You can check by doing `which popper` . And also see the content of `$PATH` and see what other folders might have the `popper` binary in them that might be getting picked instead of the one you'd like to use.

The safest bet to test is to install using `curl` but without moving to `/usr/local/bin` and then invoke popper by doing `./popper`.

**Comment by phesse001** [comment]
Worked with the latest branch! Thank you so much for taking the time to work through this with me Ivo, I appreciate it!

**Comment by ivotron** [comment]
awesome! I'm glad it worked, happy to help :-D
